name: Android CI

on:
  push:
    branches:
      - main  # Run the workflow on push to main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # This sets the JDK distribution to Temurin (AdoptOpenJDK successor)
        java-version: '11'

    - name: Download dependencies
      run: ./gradlew build

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
