name: Android CI

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow при pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Использовать JDK Temurin (наследник AdoptOpenJDK)
        java-version: '17'

    - name: Download dependencies
      run: ./gradlew build

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git tag -a v1.0.0 -m "Release version 1.0.0"  # Укажите версию релиза
        git push origin v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используйте секретный токен GitHub

    - name: Upload Release APK
      if: github.ref == 'refs/tags/v1.0.0'  # Запускать только если есть тег v1.0.0
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create GitHub Release
      if: github.ref == 'refs/tags/v1.0.0'  # Запускать только если есть тег v1.0.0
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используйте секретный токен GitHub
