name: Android CI

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download dependencies
      run: ./gradlew clean build

    - name: Run Lint
      run: ./gradlew lint

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html
